# Generated by Django 3.0.7 on 2020-07-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200714_1120'),
        ('register_extra_hour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahour',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employers.Employer'),
            preserve_default=False,
        ),
    ]
