# Generated by Django 3.0.7 on 2020-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0002_registerextrahour_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahour',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
