# Generated by Django 3.0.7 on 2020-07-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('departaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
            preserve_default=False,
        ),
    ]
